# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rxp-twPInIPFOWmkCpG3urEw_IrwVg8T
"""

from fastapi import FastAPI
from fastapi.responses import JSONResponse
import asyncio
import requests
import whisper

from playwright.async_api import async_playwright

app = FastAPI()

IR_URL = "https://www.cathayholdings.com/holdings/ir/financial_information/results_presentation"

DATA = {
    "first_name": "",
    "last_name": "",
    "email": "",
    "telephone": ""
}

MP3_FILE = "cathay_webcast.mp3"

# Whisper model
model = whisper.load_model("medium")

# =========================
# crawler
# =========================

async def crawl_webcast():

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True,
            args=["--no-sandbox"]
        )

        page = await browser.new_page()

        # IR page
        await page.goto(IR_URL)
        await page.wait_for_timeout(5000)

        # 抓 event
        links = await page.query_selector_all("a")

        events = []

        for a in links:

            href = await a.get_attribute("href")

            if href and "zucast.com/webcast" in href:
                events.append(href)

        event_url = events[2]

        # event
        await page.goto(event_url)
        await page.wait_for_timeout(5000)

        # form
        await page.fill("input.first_name", DATA["first_name"])
        await page.dispatch_event("input.first_name", "input")

        await page.fill("input.last_name", DATA["last_name"])
        await page.dispatch_event("input.last_name", "input")

        await page.fill("input.email", DATA["email"])
        await page.dispatch_event("input.email", "input")

        await page.fill("input.telephone", DATA["telephone"])
        await page.dispatch_event("input.telephone", "input")

        await page.check("input.agreement")

        await page.wait_for_timeout(2000)

        await page.click("button.submit")

        await page.wait_for_timeout(8000)

        # audio
        await page.wait_for_selector(
            "audio",
            state="attached"
        )

        audio_src = await page.get_attribute(
            "audio",
            "src"
        )

        if audio_src.startswith("//"):
            audio_src = "https:" + audio_src

        # download mp3
        r = requests.get(audio_src)

        with open(MP3_FILE, "wb") as f:
            f.write(r.content)

        await browser.close()

        return audio_src

# =========================
# API
# =========================

@app.get("/")
async def home():

    return {
        "message": "Cathay Webcast API Running"
    }

@app.get("/run")
async def run():

    try:

        audio_url = await crawl_webcast()

        # Whisper
        result = model.transcribe(
            MP3_FILE,
            language="en",
            fp16=False
        )

        transcript = result["text"]

        return JSONResponse({
            "status": "success",
            "audio_url": audio_url,
            "transcript": transcript[:5000]
        })

    except Exception as e:

        return JSONResponse({
            "status": "error",
            "message": str(e)
        })